version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: franchise-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: franchise-app
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/franchise_db
    ports:
      - "8080:8080"

volumes:
  mongo-data:
